Initial security support in tenant manager
Apicurio/apicurio-registry pull request #1594
Opened 2021-06-17 15:20 UTC by carlesarnal

2021-06-17 17:42 UTC, carlesarnal commented
The native images build will probably fail due to the HTTP permissions. We will probably need to port the mechanism that I've implemented for the registry to the tenant-manager.

2021-06-21 07:04 UTC, carlesarnal commented
@EricWittmann @famartinrh this is ready for review

2021-06-21 12:05 UTC, famartinrh commented on multitenancy/tenant-manager-api/src/test/java/io/apicurio/multitenant/TenantManagerClientAuthTest.java
> +@Tag(ApicurioTestTags.DOCKER)
if you are adding this tag you need to configure `maven-surefire-plugin` in this projects pom.xml file the same way it's configured in `app` module, basically add this:
```
<build>
  <plugins>
    <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <groups>${groups}</groups>
                    <systemProperties>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    </systemProperties>
                </configuration>
            </plugin>
  </plugins>
</build>
```
```
<profiles>
        <profile>
            <id>no-docker</id>
            <properties>
                <groups>!docker</groups>
            </properties>
        </profile>
</profiles>
```

2021-06-21 19:56 UTC, EricWittmann requested changes
LGTM just need to make Fabian's suggested change I think.

2021-06-22 10:43 UTC, merged