Added --insecure into Export Utils
Apicurio/apicurio-registry pull request #2422
Opened 2022-04-11 08:51 UTC by SafarMirek

This PR adds --insecure parameter into Confluent Export Util and also into Apicurio Registry V1 Export Util to allow insecure HTTPS connections.

`--insecure` This option makes the client to trust all SSL certificates. 

This allows users to use self-signed certs.

2022-04-12 18:21 UTC, EricWittmann commented
LGTM @carlesarnal can you also sign off?

2022-04-13 07:48 UTC, carlesarnal commented on utils/exportConfluent/src/main/java/io/apicurio/registry/utils/export/Export.java
> +            ex.printStackTrace();
Don't print stacktraces. Create a logger and log the exception properly.

2022-04-13 07:48 UTC, carlesarnal commented on utils/exportConfluent/src/main/java/io/apicurio/registry/utils/export/Export.java
> +            ex.printStackTrace();
Same here

2022-04-13 07:52 UTC, carlesarnal requested changes
Overall lgtm, just some minor comments. Since this is a Quarkus app, you should not use System.print, you should create a proper logger and log the exceptions as required.

2022-04-25 16:57 UTC, EricWittmann approved these changes

2022-04-25 16:57 UTC, merged