Confluent Compatibility Layer - artifact referencedby endpoint
Apicurio/apicurio-registry pull request #2607
Opened 2022-07-04 10:11 UTC by SafarMirek

This PR fixes the confluent compatibility layer endpoint artifact referencedby to return list of content ids, that references that artifact.

2022-07-07 15:13 UTC, EricWittmann commented
@SafarMirek There are build errors.  Could you take a look at them?

2022-07-08 19:15 UTC, SafarMirek commented
Okay, there is a problem when tests cannot clear artifacts, because of artifact references FK constraint and question for you guys - what should happen, when content references artifact, that is going to be deleted. @carlesarnal @EricWittmann

2022-07-11 10:12 UTC, carlesarnal commented
> Okay, there is a problem when tests cannot clear artifacts, because of artifact references FK constraint and question for you guys - what should happen, when content references artifact, that is going to be deleted. @carlesarnal @EricWittmann

If the content is deleted, the references in the references table should be deleted as well, IMO.

2022-07-14 11:50 UTC, SafarMirek commented
Okay, I have fixed that deleting content deletes also its rows in references table.

There is still problem, that you need to delete artifacts in right order to successfully delete them. I have fixes that allowing multiple attempts to delete artifacts at the end of the IT. This does not solve big references trees and also will fail if there is a ref cycle - for example Artifact1 version 1 references Artifact2 version 1 and Artifact2 version 2 references Artifact1 version 1. There is no right order of deleting artifacts and there is a need for deleting artifact versions in right order (delete A2:2, then A1:1 and then A2:1). 

**Suggested solution:**
Create an endpoint for delete all user data (used in tenant manager to delete tenants) and use that in teardown phase of integration tests.

2022-07-18 13:34 UTC, carlesarnal requested changes
One comment about the implementation of the method in the legacyId mode.

2022-07-18 13:34 UTC, carlesarnal commented on app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
> +                version -> storage.getContentIdsReferencingArtifact(null, subject, version));
Actually, when working in the legacyId mode, this method must return the list of global ids, instead of the list of content ids.

2022-07-19 14:41 UTC, carlesarnal commented on app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
> +                version -> storage.getContentIdsReferencingArtifact(null, subject, version));
This is exactly what I meant, except that we should implement a new query to get the relation of globalIds from a contentId set. Let me know if you need/want some help with it.

2022-07-26 08:44 UTC, carlesarnal approved these changes
Overall LGTM

2022-08-11 18:14 UTC, EricWittmann commented
@SafarMirek this is ready to merge, correct?

2022-08-11 18:34 UTC, SafarMirek commented
> @SafarMirek this is ready to merge, correct?

Yes!

2022-08-11 18:48 UTC, merged