Fix Owner Validation
Apicurio/apicurio-registry pull request #3593
Opened 2023-08-21 16:02 UTC by renjingxiao

Hi @EricWittmann  and @carlesarnal ,

In this PR I have added checks for the `owner` to ensure it's neither `null` or an empty string. `MissingRequiredParameterException` will be thrown if the check fails.

It will close #3476 .

Thank you for reviewing.

2023-08-23 12:09 UTC, carlesarnal commented on app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
> +        requireParameter("owner", owner);
Is calling the `requireParameter` method not sufficient for this purpose?

2023-08-23 12:09 UTC, carlesarnal requested changes
Please address the feedback or reply to the comment.

2023-08-23 12:21 UTC, renjingxiao commented
Hi @carlesarnal , thank you for the review. I thought `requireParameter` only checks for `null`, so I added lines 264-266 to check if it's an empty value. If they are redundant I'll remove them.

2023-08-29 11:34 UTC, renjingxiao commented
Hi @carlesarnal , 
I have added the unit tests. Could you please have a look? 
Thank you

2023-08-29 16:11 UTC, EricWittmann approved these changes
Looks perfect, thanks @renjingxiao

2023-08-29 16:11 UTC, merged