Preserve global IDs when exporting from Confluent
Apicurio/apicurio-registry pull request #4012
Opened 2023-11-20 22:24 UTC by prestona

This changes preserves global IDs in the .zip file generated by "exportConfluent", and now matches the behavior of exporting data from an Apicurio registry.

2023-11-21 17:09 UTC, EricWittmann commented
Thanks @prestona - we'll take a look asap.

2023-11-24 08:39 UTC, carlesarnal requested changes
Thanks for the contribution! I have left a comment about the change, let me know what you think.

2023-11-24 08:39 UTC, carlesarnal commented on utils/exportConfluent/src/main/java/io/apicurio/registry/utils/export/Export.java
> +        versionEntity.globalId = metadata.getId();
In my view, this should not be the case. Note that, if you have producers/consumers using Confluent's Schema Registry and want to move to Apicurio Registry using this tool, the equivalent of their globalId would be the contentId, not our globalId, thus why the globalId is being autogenerated. At the very minimum, this option should be put behind an option.

2023-11-29 12:59 UTC, prestona commented
Clearly this PR isn't useful, and I should just use "contentId". Closing.

2023-11-29 12:59 UTC, closed without merging