Add artifact created event based on the outbox pattern
Apicurio/apicurio-registry pull request #5274
Opened 2024-09-30 12:19 UTC by carlesarnal

2024-10-04 12:19 UTC, EricWittmann commented on app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlFactory.java
> +    @Info(category = "storage", description = "Kafka sql storage event topic")
Isn't there some kind of `sinceVersion` property we can configure for this?

2024-10-04 12:20 UTC, EricWittmann commented on app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlFactory.java
> +    @Info(category = "storage", description = "Kafka sql storage event topic")
Same with any other config property introduced in this PR....

2024-10-04 12:24 UTC, EricWittmann commented on app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
> +    private void deleteEvent(String eventId) {
I tried to have a pattern in the SQL storage where only public methods would call `handles.withHandle()` - the resulting `handle` instance would get passed as an argument to private methods needing it.  Could you change this to follow that pattern?

2024-10-04 12:30 UTC, EricWittmann requested changes
Looks good.  Nice testing.  I had a couple minor comments.

2024-10-09 14:55 UTC, EricWittmann approved these changes
LGTM as-is.  However, question for you:

Do we ever want to offer the option of SQL storage variant + Kafka eventing **without** using Debezium?

2024-10-10 06:44 UTC, carlesarnal commented
> LGTM as-is. However, question for you:
> 
> Do we ever want to offer the option of SQL storage variant + Kafka eventing **without** using Debezium?

Good question. If the Kafka cluster is there anyway, what would be the reason to not use Debezium? In the end, what we're doing is very basic CDC, so I don't see any benefits other than simplifying (a bit) the deployment model. For now, I'll merge as-is, we can revisit later if we think it makes sense.

2024-10-10 06:44 UTC, merged